### ISSUE TITLE
Navigation over homogeneous ground

### ISSUE THREAD

**Issue by SaschaHeymann** [doublerobotics/d3-sdk#1]
We have a problem when we drive over our industrial floor which is grey and shiny.

Observation: The D3 then drives very slowly and cannot find its way to the navigation point. Often a cash from the D3 service is the result.

With a carpet or inhomogeneous pattern of the floor the navigation works very well.
I could share photos and videos if necessary.

**Comment by davidcann** [comment]
We have seen an issue on some glossy floors with overhead spotlights causing blind spots for the depth sensors. The system interprets this as unknown/unsafe ground, so attempts to drive around it – but the reflections keep changing/moving depending on the angle. We are working on a better way to filter out these reflections and hope to improve this significantly in an update.

If you'd like to confirm that what you're seeing is what we're working on addressing, please email support@doublerobotics.com and provide a Visitor Pass for us to call in and collect a sample of data from the affected area.

As a temporary workaround, if your unit is in Developer Mode, you can enable an option for the driver to choose to temporarily disable obstacle avoidance to get through an affected area. Send the command "endpoint.setOptions" with parameters: { "allowDisablingObstacleAvoidance": true }. The driver will get a new option under the "extra" options menu (top right) during a call.

> Often a cash from the D3 service is the result.

Can you explain what you mean by this?

**Comment by SaschaHeymann** [comment]
Thank you the workaround works fine. Now i can navigate also in the charging dock.
This is an snapshot of the area which is difficult to drive with switched on ObstacleAvoidance: ![image](https://user-images.githubusercontent.com/35559519/88521417-29983700-cff5-11ea-89cf-5d27e1a6c06e.png)

>Often a cash from the D3 service is the result.
>Can you explain what you mean by this?
This is an issue which is caused by our currently unstable Wifi Mash. The D3 only reconnects automatically to the configured Wifi  after a "hard" reboot.

**Comment by davidcann** [comment]
That floor actually looks like it will probably be ok for the depth sensors. It may be that they're slightly mis-calibrated. We can't tell if this will interfere with obstacle avoidance without seeing the floor depth data. Note that it is expected that some of the edges will be missing dots, especially the bottom left and right sections while the camera is tilted down all the way – this is due to limitations of how wide the depth sensor cameras can see. The front depth sensor can usually see floor up to 10 meters away, but this may be lower depending on the environment.

We'd like to evaluate the calibration of your unit. If you can send your base or head serial number to devteam@doublerobotics.com, our team can help with that.
