### ISSUE TITLE
Unlimit max rotation speed

### ISSUE THREAD

**Issue by KimMingyeol** [doublerobotics/d3-sdk#6]
Hi, I'm exploring D3 api, and all the commands to rotate a d3 robot (e.g. navigate.drive, ptz.move) seem to set an upper limit on its rotation speed.
I wanna have full control over its rotation speed, so I wonder if there's any way to unlimit or change the maximum rotation speed.

**Comment by davidcann** [comment]
The sustained turning speed is not designed to be very fast, partly because it would be a poor/disorienting user experience for a remote driver. While you can decrease the speed by sending a float value between -1 and 1, there isn't a way to increase the maximum sustained turn speed.

You may get a faster short burst turn speed by using the base.turnBy command, which takes a specific angle and the base attempts to turn by that amount as fast as it can.
